### ISSUE TITLE
Different color in help for the referenced arguments

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1746]
If we have something like this in the command YAML:
```yaml
  - name: yt
    cname: yank_to
    summary: Copy [len] bytes from current seek to [offset]
    args:
      - name: len
        type: RZ_CMD_ARG_TYPE_RZNUM
      - name: offset
        type: RZ_CMD_ARG_TYPE_RZNUM
```
Then it would be nice to parse the `summary` and `detail` fields to detect the argument names in the `[``]` brackets, to highlight them with different color in the help message.
In this case they are `[len]` and `[offset]`
