### ISSUE TITLE
Migrate static build to Meson

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#340]
Currently the static build achieved by `sys/static.sh`. With migration to Meson it should be dropped and rewritten for the Meson/Ninja. See also CI:
https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L349
```yaml
  build-static:
    name: Build static
    # FIXME: ignore error until all tests properly pass
    continue-on-error: true
    if: contains(github.head_ref, 'static') || contains(github.ref, 'release-') || github.event_name == 'schedule'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - name: Checkout our Testsuite Binaries
      uses: actions/checkout@v2
      with:
          repository: rizinorg/rizin-testbins
          path: test/bins
    - name: Install static
      run: |
        ./sys/static.sh
        sudo make symstall
```
