### ISSUE TITLE
test/unit/test_dwarf and test/unit/test_dwarf_info fail on Alpine Linux static build

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#350]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Alpine Linux (Edge) x86_64
| File format of the file you reverse (mandatory)      | DWARF
| Architecture/bits of the file (mandatory)            | x86/64
| rizin -v full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/4805f845d3a72d058b79048e809a594f4d3634f1

### Expected behavior

All tests pass

### Actual behavior

Segfaults on the `test_big_endian_dwarf2` from `test/unit/test_dwarf` and `test_dwarf2_big_endian` from `test/unit/test_dwarf_info`.

```
74/74 vector               OK             0.00s

The output from the failed tests:

29/74 dwarf                FAIL           0.47s (killed by signal 11 SIGSEGV)

--- command ---
10:24:02 /__w/rizin/rizin/rizin/build/test/unit/test_dwarf
--- stdout ---
test_dwarf_cpp_empty_line_info OK
-------

30/74 dwarf_info           FAIL           0.37s (killed by signal 11 SIGSEGV)

--- command ---
10:24:02 /__w/rizin/rizin/rizin/build/test/unit/test_dwarf_info
--- stdout ---
test_dwarf3_c OK
-------


Summary of Failures:

29/74 dwarf                FAIL           0.47s (killed by signal 11 SIGSEGV)
30/74 dwarf_info           FAIL           0.37s (killed by signal 11 SIGSEGV)

Ok:                 72  
Expected Fail:      0   
Fail:               2   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /__w/rizin/rizin/rizin/build/meson-logs/testlog.txt
ninja: job failed: /usr/bin/meson test --no-rebuild --print-errorlogs
ninja: subcommand failed
```

### Steps to reproduce the behavior
```yaml
  build-static:
    name: Build static
    # FIXME: ignore error until all tests properly pass
    continue-on-error: true
    if: contains(github.head_ref, 'dist') || contains(github.head_ref, 'static') || contains(github.ref, 'release-') || github.event_name == 'schedule'
    runs-on: ubuntu-20.04
    container: alpine:edge
    steps:
    - name: Install dependencies
      run: apk add --no-cache git gcc g++ linux-headers cmake wget unzip py3-wheel py3-setuptools py3-pip meson ninja
    - name: Checkout rizin
      run: |
        git clone https://github.com/${{ github.repository }}
        cd rizin
        git fetch origin ${{ github.ref }}
        git checkout -b local_branch FETCH_HEAD
        git submodule init
        git submodule update
    - name: Checkout our Testsuite Binaries
      run: git clone https://github.com/rizinorg/rizin-testbins test/bins
      working-directory: rizin
    - name: Compile with meson
      run: |
        CFLAGS="-static" LDFLAGS="-static" meson --prefix=${HOME}/.local --buildtype release --default-library static build
        ninja -C build && ninja -C build install
      working-directory: rizin
    - name: Run unit tests
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        ninja -C build test
      working-directory: rizin
    - name: Run tests
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        rizin -v
        rz-test -v
        cd test
        rz-test -L -o results.json
```
