### ISSUE TITLE
Consider using TOML for SDB source files

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3589]
Currently SDB reads and compiles from the source file looking like `K.K = V`, which is hard to read for multiple levels of nestness. 
See e.g. files in `librz/analysis/d/*.txt`

I propose using TOML (see [v1.0.0 specification](https://toml.io/en/v1.0.0)) for that, there is a good parsing library in C: https://github.com/cktan/tomlc99

Compare 
```
_EXCEPTION_RECORD=struct
struct._EXCEPTION_RECORD=ExceptionCode,ExceptionFlags,ExceptionRecord,ExceptionAddress,NumberParameters,ExceptionInformation
struct._EXCEPTION_RECORD.ExceptionCode=DWORD,0,0
struct._EXCEPTION_RECORD.ExceptionFlags=DWORD,4,0
struct._EXCEPTION_RECORD.ExceptionRecord=struct _EXCEPTION_RECORD*,8,0
struct._EXCEPTION_RECORD.ExceptionAddress=PVOID,16,0
struct._EXCEPTION_RECORD.NumberParameters=DWORD,24,0
struct._EXCEPTION_RECORD.ExceptionInformation=ULONG_PTR[15],28,0

EXCEPTION_RECORD=typedef
typedef.EXCEPTION_RECORD=struct _EXCEPTION_RECORD
```
to 
```toml
[_EXCEPTION_RECORD]
kind="struct"
members = ["ExceptionCode", "ExceptionFlags", "ExceptionRecord", "ExceptionAddress", "NumberParameters", "ExceptionInformation" ]
ExceptionCode.type="DWORD"
ExceptionCode.count=1 # this one is optional and always one element if not specified
ExceptionCode.offset=0 # this one is optional and always calculated from type if not specified
# we omit these optional fields in the future records
ExceptionFlags.type="DWORD"
ExceptionRecord.type="struct _EXCEPTION_RECORD*"
ExceptionAddress.type="PVOID"
NumberParameters.type="DWORD"
ExceptionInformation.type="ULONG_PTR[15]"

[EXCEPTION_RECORD]
kind="typedef"
base="struct _EXCEPTION_RECORD"
```

You can see, that TOML files are much more readable and easier to write.

Same applies to some other SDB source files - calling conventions, etc.
