### ISSUE TITLE
Convert Debian CI jobs from ACR to Meson

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#394]
**Is your feature request related to a problem? Please describe.**
Before #393 we must ensure all CI jobs run with Meson, otherwise we can't kill ACR/Make.

**Describe the solution you'd like**
Use python3 on those old debian distros or compile python3 for them and use Meson to install Rizin there.

**Describe alternatives you've considered**
If native compilation won't work, cross-compilation is still an option.

**Comment by XVilka** [comment]
We already compile Python there: https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L318
```yaml

    - name: Install tools
      run: apt-get update && apt-get install --yes patch unzip git gcc make curl pkg-config libc6-i386 build-essential
    - name: Install Python source build dependcies
      run: apt-get install --yes checkinstall libbz2-dev libc6-dev libgdbm-dev libncursesw5-dev libreadline-gplv2-dev libssl-dev libsqlite3-dev tk-dev
    - name: Install Python from source
      run: |
        curl -o Python-3.6.11.tgz https://www.python.org/ftp/python/3.6.11/Python-3.6.11.tgz
        tar -zxvf Python-3.6.11.tgz
        cd Python-3.6.11/
        ./configure
        make install
```
