### ISSUE TITLE
newshell: when details are available for a group, they should be shown/added for all sub-commands

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#81]
Some commands are very similar (e.g. `wv`, `wv2`, `wv8`, etc.) so it may not have a lot of sense to duplicate all the examples for all subcommands of `wv`. Instead we may just define a `details` section at the `wv` level and "inherit" it in all subcommands (wv1, wv2, wv4, wv8).
```yaml
    - name: wv
      summary: Write value of given size
      subcommands:
        - name: wv
          cname: write_value
          summary: Write value as 4-bytes/8-bytes based on value
          args:
            - name: value
              type: RZ_CMD_ARG_TYPE_NUM
        - name: wv1
          cname: write_value1
          summary: Write value of 1 byte
          args:
            - name: value
              type: RZ_CMD_ARG_TYPE_NUM
        - name: wv2
          cname: write_value2
          summary: Write value of 2 byte
          args:
            - name: value
              type: RZ_CMD_ARG_TYPE_NUM
        - name: wv4
          cname: write_value4
          summary: Write value of 4 byte
          args:
            - name: value
              type: RZ_CMD_ARG_TYPE_NUM
        - name: wv8
          cname: write_value8
          summary: Write value of 8 byte
          args:
            - name: value
              type: RZ_CMD_ARG_TYPE_NUM
      details:
        - name: Examples
          entries:
            - text: wv
              arg_str: " 0xdeadbeef"
              comment: Write the value 0xdeadbeef at current offset
            - text: wv2
              arg_str: " 0xdead"
              comment: Write the word 0xdead at current offset
            - text: wv1
              arg_str: " 0xde"
              comment: Write the byte 0xde at current offset
```
